### ISSUE TITLE
App Force Closes on exiting Settings page.

### ISSUE THREAD

**Issue by SanchithHegde** [jahirfiquitiva/Kuper#10]
###### Device/dashboard info:
 - Kuper version: `1.1.5`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G3`
 
###### Reproduction Steps:

1. Open app built with Kuper.
2. Tap on 3-dot menu.
3. Tap on Settings. The Settings page opens.
4. Exit Settings page by using Back button.
5. App force closes.

###### Notes:

 - This has also been tested on other devices with 7.1.2 with same result.

**Comment by jahirfiquitiva** [comment]
Please add logs

**Comment by SanchithHegde** [comment]
Here you go @jahirfiquitiva .

[Filtered log](https://github.com/jahirfiquitiva/Kuper/files/1659288/log_filtered.txt) displaying only logs related to my app.

[Full verbose level log](https://github.com/jahirfiquitiva/Kuper/files/1659290/log.txt) displaying everything.
