### ISSUE TITLE
App doesn't allow users to select all images as a source in Muzei.

### ISSUE THREAD

**Issue by SanchithHegde** [jahirfiquitiva/Kuper#11]
###### Dashboard info:
 - Kuper version: `1.1.5`

###### Issue:
If we allot the images in the app as a source for wallpapers in Muzei, it allows us to select only **Favourites** and not all the images we included. And since no favourites can be assigned in Kuper, no images can be selected.

**Comment by jahirfiquitiva** [comment]
Please test this version code: `263c097`

**Comment by jahirfiquitiva** [comment]
@SanchithHegde  Is this fixed in the new version?

**Comment by SanchithHegde** [comment]
@jahirfiquitiva Not yet. No walls are set from the app.
