### ISSUE TITLE
Zooper icon is shown for Kolorette in "Setup" page

### ISSUE THREAD

**Issue by SanchithHegde** [jahirfiquitiva/Kuper#12]
###### Device/dashboard info:
 - Kuper version: `1.1.6` 

###### Issue:
Instead of the Kolorette icon, Zooper icon is shown for Kolorette in "Setup" page.

###### Requests:
 - Display Kolorette icon (instead of Zooper icon shown as of now) because Kustom apps can also use Kolorette.
 - Display string next to icon as "Required to use assets included." due to the above mentioned reason. 

Thanks ahead of time!

**Comment by jahirfiquitiva** [comment]
Please fill the issues template with **everything** it includes. Additional information is welcome, but the template must be filled properly.

**Comment by SanchithHegde** [comment]
###### Device/dashboard info:
 - Kuper version: `1.1.6`

###### Reproduction Steps

1. Enable Kolorette bool in Android Studio in `kuper_configs.xml` file. Build app.
2. Open app. Setup page is opened by default.

###### Expected Result
 - Kolorette icon is shown next to "Kolorette" text.
 - "Required to use assets included." string shown below "Kolorette" text, because all Kustom apps can use Kolorette.

###### Actual Result
 - Zooper icon is shown next to "Kolorette" text.
 - "Required to use widgets included." string shown below "Kolorette" text.
