### ISSUE TITLE
Add rounded corners

### ISSUE THREAD

**Issue by sarsa2703** [jahirfiquitiva/Kuper#39]
This would be great if you add an option to adjust the roundness of buttons, dialogues.

**Comment by jahirfiquitiva** [comment]
Use the proper template

**Comment by jahirfiquitiva** [comment]
https://github.com/jahirfiquitiva/Kuper/issues/new?template=feature_request.md

**Comment by jahirfiquitiva** [comment]
I'll think about it. Next time, use the proper issue template.

Also, there's no such thing as Material Design 2.0 ... It's called Material Theming, and the current style of Kuper could be considered my own style of Material Theming.

Although I agree there could be an option to let you customize it.

It will take some time to implement tho.
