### ISSUE TITLE
'Missing apps' is still showing after removing the asset folders.

### ISSUE THREAD

**Issue by kushjain94** [jahirfiquitiva/Kuper#51]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Kuper Version: `2.2.9`
 - Android version: `10`
 - Device Manufacturer: `Samsung`
 - Device Name: `M30`

### Describe the bug
Missing apps screen is still showing after removing the asset folders.
Apps showing - zooper widgets pro, klck and klck pro. I only have kustom widgets which are showing fine in the app.

![Screenshot_20200520-231836_Exquigets](https://user-images.githubusercontent.com/35252842/82479923-ab00b400-9af0-11ea-8ad9-d1fa032fea79.jpg)

**Comment by jahirfiquitiva** [comment]
Mind adding details about what kind of assets have you added and what apps are still shown?

**Comment by kushjain94** [comment]
Updated.

**Comment by jahirfiquitiva** [comment]
Fixed in v `2.2.0`
