### ISSUE TITLE
Widgets can be accessed even when license checker identifies invalid license.

### ISSUE THREAD

**Issue by Not-Dhanraj** [jahirfiquitiva/Kuper#63]
### Requirements

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

### Kuper Version

any

### Android Version

any

### Device Manufacturer

any

### Device Name

any

### What happened?

Widgets can be accessed through kwgt even when license check identifies invalid license in any device. I think same can be said for klwp and klck

### Reproduction Steps

Get a apk of any of app based on kuper with license checker. Follow the provided video below to reproduce bug.

### Expected behavior

When license checker fails then widgets should't be shown in kwgt.

### Screenshots or videos

https://user-images.githubusercontent.com/80586983/154321145-02c7434b-fa7c-484a-a92a-79fe29646b91.mp4

**Comment by jahirfiquitiva** [comment]
This is an android apps limitation. We cannot block access to app resources, just the app itself, so there's nothing i can do about it, sorry

**Comment by Not-Dhanraj** [comment]
Can't it be fixed using googleplay asset dilevery? 
I mean after license is confirmed as valid then user can tap a button to download all assets using play asset delivery(on-demand)

**Comment by Not-Dhanraj** [comment]
@jahirfiquitiva i found a easier and less time consuming solution for this issue.
You can simply disable kustom api `ContentProvider` by default by using `android:enabled="false"`
And then enabled it programatically using `PackageManager.COMPONENT_ENABLED_STATE_ENABLED` after license validation.

**Comment by jahirfiquitiva** [comment]
@Not-Dhanraj thanks for the information, I will take a look and try to use it in a future update
