### ISSUE TITLE
Missing Apps shows the apps I had installed

### ISSUE THREAD

**Issue by Nevodev** [jahirfiquitiva/Kuper#66]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Kuper Version

2.3.8

### Android Version

13.0.0

### Device Manufacturer

Google

### Device Name

Pixel 4

### What happened?

I have installed KWGT, pro key, KLWP, but the missing apps still shows me that I didn't install these apps.
![Uploading Screenshot_20220604-223343.png…]()

### Reproduction Steps

Install KWGT
Open the app

### Expected behavior

The missing apps doesn't show the apps that I installed

**Comment by Nevodev** [comment]
![Screenshot_20220604-223343](https://user-images.githubusercontent.com/51047891/172007904-3d395888-0874-4570-bca7-70129eccee74.png)

**Comment by SpDly14** [comment]
It wouldn't show this if you have downloaded the app from PlayStore instead of apk

**Comment by RydahDoesTech** [comment]
Is there any progress on this? I'm using Kuper 2.4.0 and experiencing the same issue. I did notice when I change the target SDK, that resolves the issue however that causes other issues.

**Comment by jahirfiquitiva** [comment]
@RydahDoesTech no progress on this yet, I have been really busy, sorry.

**Comment by jahirfiquitiva** [comment]
Fixed in Kuper `2.4.1`
