### ISSUE TITLE
KLCK templates open Play Store page instead of the app even when installed

### ISSUE THREAD

**Issue by pixwalls** [jahirfiquitiva/Kuper#8]
###### Device/dashboard info:
 - Kuper version: `1.1.5`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 3T`

###### Reproduction Steps

1. Open Kuper
2. Click on a lock screen template in the widgets tab
3. Playstore page of KLCK is opened

###### Expected Result
Open the respective template in the KLCK app, because it is installed.

###### Actual Result
Opens the KLCK play store page

**Comment by jahirfiquitiva** [comment]
Does this happen with other templates too? KWGT, and KLWP ??

**Comment by pixwalls** [comment]
Checked KWGT and yes, the problem is there as well.

**Comment by jahirfiquitiva** [comment]
Thanks for the info @pixwalls

**Comment by SanchithHegde** [comment]
Yup, it opens up the Play Store page of the corresponding Pro Key app.

**Comment by jahirfiquitiva** [comment]
@pixwalls @SanchithHegde 

I need more info to understand the best way to fix this:

1. Which version do users need to be able to use the assets? Normal? Pro? Both?
2. Which version do users need to be able to open the assets from the app? Normal? Pro? Both?

**Comment by jahirfiquitiva** [comment]
Please test a new version which code is: `263c097`

**Comment by SanchithHegde** [comment]
@jahirfiquitiva 
1, 2: Both apps are needed to load and use the assets included in the app. It is the same for all Kustom apps. 
The pro app does nothing on its own, it's just a licence key.

**Comment by jahirfiquitiva** [comment]
@SanchithHegde 
So we would need to ask the users to download both, right?

**Comment by SanchithHegde** [comment]
@jahirfiquitiva Yup. You are right.
