### ISSUE TITLE
Open in KWGT Button Doesn't Work in Recent Versions

### ISSUE THREAD

**Issue by kolepsd** [jahirfiquitiva/Kuper#86]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Kuper Version

2.4.7

### Android Version

14

### Device Manufacturer

Google

### Device Name

Pixel 7 Pro

### What happened?

The button that lets you open a widget in KWGT hasn't worked for a few of the more recent versions.

### Reproduction Steps

1. Open app
2. Tap button to open a widget in KWGT

### Expected behavior

Tapping the button should open the desired widget inside of the KWGT app but no longer does anything when tapped.

### Screenshots or videos

Screenshot link: [](https://imgur.com/KPq3YwX)

-----

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jahirfiquitiva/Kuper/issues/86">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/86/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/86/pledge.svg">
</picture>
</a>

**Comment by jahirfiquitiva** [comment]
You can pledge behind and help support this effort using Polar.sh


<a href="https://polar.sh/jahirfiquitiva/Kuper/issues/86">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/86/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/86/pledge.svg">
</picture>
</a>

**Comment by jahirfiquitiva** [comment]
Fixed in v 2.4.9
