### ISSUE TITLE
Predictive Back Gesture Support

### ISSUE THREAD

**Issue by kolepsd** [jahirfiquitiva/Kuper#87]
### Kuper Version

2.4.7

### Describe the feature

Android 13 adds a new feature called "predictive back gesture". It basically just makes the back gesture smoother and lets you preview where you'll be going before fully initiating the gesture. 

Here's a screen recording I did to show what it looks like in apps that support it: https://youtube.com/shorts/YDNOi-2WqXw?feature=share

**Comment by jahirfiquitiva** [comment]
Duplicate of https://github.com/jahirfiquitiva/Frames/issues/256
