### ISSUE TITLE
Bug for Android 13 

### ISSUE THREAD

**Issue by Ahmadansari2233** [jahirfiquitiva/Kuper#91]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Kuper Version

2.4.9

### Android Version

13

### Device Manufacturer

Xiaomi 

### Device Name

11x Pro

### What happened?

When I try to open app after makeing Kwgt then app is not working smoothly or proper many time facing Crashed issues please fix it thanks

### Reproduction Steps

App Crashed every time please fix it

**Comment by jahirfiquitiva** [comment]
Duplicate of #80

**Comment by jahirfiquitiva** [comment]
@Ahmadansari2233 please include the logs for the crash in issue #80
