### ISSUE TITLE
Enable notifications on Kuper

### ISSUE THREAD

**Issue by finssao** [jahirfiquitiva/Kuper#93]
![Capture d'écran 2023-12-08 175607](https://github.com/jahirfiquitiva/Kuper/assets/55627912/75904734-247f-4e1f-b683-8fc40a201265)
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Kuper Version

2.4.9

### Android Version

14.0.0

### Device Manufacturer

Google

### Device Name

Pixel A

### What happened?

Unresolved reference: OneSignal 

### Reproduction Steps

Unresolved reference: OneSignal

**Comment by jahirfiquitiva** [comment]
You can pledge behind and help support this effort using Polar.sh


<a href="https://polar.sh/jahirfiquitiva/Kuper/issues/93">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/93/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/93/pledge.svg">
</picture>
</a>

**Comment by jahirfiquitiva** [comment]
Given this message on the discord server, notifications are working correctly. It was an issue with the setup and not the dashboard functionality. Therefore, I'm closing this issue

https://discord.com/channels/702900511963086978/702902284283150436/1183056273843957761
