### ISSUE TITLE
Background for Widgets grid items

### ISSUE THREAD

**Issue by finssao** [jahirfiquitiva/Kuper#94]
### Kuper Version

2.4.9

### Describe the feature

display the user's wallpaper or image or color instead of the gray background
![Capture d'écran 2023-12-12 151449](https://github.com/jahirfiquitiva/Kuper/assets/55627912/0b9aed3f-c62a-40de-b0a2-8d1b1dd7d04c)

-----

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jahirfiquitiva/Kuper/issues/94">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/94/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/94/pledge.svg">
</picture>
</a>

**Comment by jahirfiquitiva** [comment]
You can pledge behind and help support this effort using Polar.sh


<a href="https://polar.sh/jahirfiquitiva/Kuper/issues/94">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/94/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Kuper/issues/94/pledge.svg">
</picture>
</a>

**Comment by jahirfiquitiva** [comment]
Fixed* in Kuper 2.5.0


* For Android 13+ the app will show the device's default wallpaper. It's a limitation in the Android app permissions
